### PR TITLE
MacOS/BSD compatiblity

### PR DESCRIPTION
**Pull request by NeoRaider**
Let's hope there aren't any more incompatible `qsort_r` definitions...

### CODE REVIEW

**Comment by tcatm** [comment]
`exit_error()` should still allow format strings like `error()` does.

**Comment by NeoRaider** [comment]
I tried not to introduce unnecessary code, the usage message was the only place where the format string was actually used.

Would you be okay with a macro definition, like in http://git.openwrt.org/?p=openwrt.git;a=commitdiff;h=76dde10b2061b8fedf88c38712fc054219a934d9 ?

**Comment by tcatm** [comment]
The macro looks fine.

**Comment by NeoRaider** [comment]
Updated. I've found an issue with the macro (it doesn't to the right thing when errnum == 0), so I've replaced it with a proper function.

**Pull request merged**
